# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftmotion_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorentry',
            name='diff',
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='vbat',
            field=models.FloatField(verbose_name='Battery Voltage'),
        ),
    ]
