# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftmotion_backend', '0002_auto_20170218_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_weight', models.FloatField(verbose_name='Load weight')),
                ('lift_rate', models.FloatField(verbose_name='LBD Lift Rate')),
                ('freq', models.FloatField(verbose_name='Frequency/Min')),
                ('ma_origin', models.FloatField(verbose_name='Moment Arm at Origin')),
                ('ma_dest', models.FloatField(verbose_name='Moment Arm at Destination')),
            ],
        ),
        migrations.CreateModel(
            name='RecordID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64, verbose_name='Company Name')),
                ('job_name', models.CharField(max_length=64, verbose_name='Job Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Employee Last Name')),
                ('first_name', models.CharField(max_length=64, verbose_name='Employee First Name')),
                ('gender', models.CharField(max_length=2, verbose_name='Gender')),
                ('date', models.DateTimeField(verbose_name='Run date')),
                ('number', models.IntegerField(verbose_name='Run number')),
                ('task_name', models.CharField(max_length=64, verbose_name='Task Name')),
                ('trial_number', models.IntegerField(verbose_name='Trial number')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='bend_acc',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='bend_vel',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='lat_acc',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='lat_bend',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='lat_pos',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='lat_twist',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='lat_vel',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='twist_acc',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='twist_vel',
        ),
        migrations.RemoveField(
            model_name='sensorentry',
            name='vbat',
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='acc_heading',
            field=models.FloatField(default=None, verbose_name='Acceleration Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='acc_pitch',
            field=models.FloatField(default=0, verbose_name='Acceleration Pitch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='delta_heading',
            field=models.FloatField(default=0, verbose_name='Delta Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='delta_pitch',
            field=models.FloatField(default=0, verbose_name='Delta Pitch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='delta_roll',
            field=models.FloatField(default=0, verbose_name='Delta Roll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='vel_heading',
            field=models.FloatField(default=0, verbose_name='Velocity Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='vel_roll',
            field=models.FloatField(default=0, verbose_name='Velocity Roll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qw_sensor1',
            field=models.FloatField(verbose_name='Quaternionw Sensor 1'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qw_sensor2',
            field=models.FloatField(verbose_name='Quaternionw  Sensor 2'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qx_sensor1',
            field=models.FloatField(verbose_name='Quaternionx  Sensor 1'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qx_sensor2',
            field=models.FloatField(verbose_name='Quaternionx  Sensor 2'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qy_sensor1',
            field=models.FloatField(verbose_name='Quaterniony  Sensor 1'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qy_sensor2',
            field=models.FloatField(verbose_name='Quaterniony  Sensor 2'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qz_sensor1',
            field=models.FloatField(verbose_name='Quaternionz  Sensor 1'),
        ),
        migrations.AlterField(
            model_name='sensorentry',
            name='qz_sensor2',
            field=models.FloatField(verbose_name='Quaternionz  Sensor 2'),
        ),
    ]
