# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftmotion_backend', '0003_auto_20170224_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordid',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, verbose_name='Gender'),
        ),
    ]
