# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftmotion_backend', '0004_auto_20170224_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorentry',
            options={'ordering': ('time_stamp',)},
        ),
        migrations.AddField(
            model_name='sensorentry',
            name='record',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='swiftmotion_backend.RecordID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordid',
            name='date',
            field=models.DateField(verbose_name='Run date'),
        ),
    ]
